name: SDK auto-tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Generate appsettings
        run: docker run --rm ghcr.io/payfurl/config-build:main > ./tests/config.json
      - name: Run tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --display-incomplete --display-skipped --display-deprecations --display-errors --display-warnings
          php_version: "7.3"
